import { ToolDefinition } from '@/types/tools';

export const toolDefinitions: ToolDefinition[] = [
  {
    slug: 'cpf-generator',
    name: 'Gerador de CPF',
    description: 'Gera e valida CPFs com ou sem mascara.',
    category: 'Identidade',
    keywords: ['cpf', 'documento', 'validar', 'gerar'],
    path: '/tools/cpf-generator',
    examples: ['123.456.789-09', '52998224725'],
  },
  {
    slug: 'cnpj-generator',
    name: 'Gerador de CNPJ',
    description: 'Gera e valida CNPJs com ou sem mascara.',
    category: 'Identidade',
    keywords: ['cnpj', 'empresa', 'validar', 'gerar'],
    path: '/tools/cnpj-generator',
    examples: ['12.345.678/0001-90', '11222333000181'],
  },
  {
    slug: 'hash-generator',
    name: 'Hash Generator',
    description: 'Gera hash MD5, SHA1, SHA256 e SHA512.',
    category: 'Segurança',
    keywords: ['hash', 'sha256', 'md5', 'checksum'],
    path: '/tools/hash-generator',
    examples: ['hello world'],
  },
  {
    slug: 'uuid-generator',
    name: 'UUID / ULID Generator',
    description: 'Gera UUID v4 e ULID em lote.',
    category: 'DevTools',
    keywords: ['uuid', 'ulid', 'id', 'gerador'],
    path: '/tools/uuid-generator',
    examples: ['10 IDs'],
  },
  {
    slug: 'lorem-ipsum',
    name: 'Lorem Ipsum',
    description: 'Gera palavras, frases e paragrafos.',
    category: 'Texto',
    keywords: ['lorem', 'texto', 'mock', 'conteudo'],
    path: '/tools/lorem-ipsum',
    examples: ['5 paragrafos'],
  },
  {
    slug: 'jwt-tool',
    name: 'JWT Encoder/Decoder',
    description: 'Decode, sign e verify de tokens JWT.',
    category: 'Segurança',
    keywords: ['jwt', 'token', 'auth', 'hs256'],
    path: '/tools/jwt-tool',
    examples: ['eyJhbGciOiJIUzI1NiJ9...'],
  },
  {
    slug: 'base64-tool',
    name: 'Base64 Encode/Decode',
    description: 'Converte texto para base64 e vice-versa.',
    category: 'Encoding',
    keywords: ['base64', 'utf-8', 'url-safe'],
    path: '/tools/base64-tool',
    examples: ['SGVsbG8='],
  },
  {
    slug: 'link-shortener',
    name: 'Encurtador de Links',
    description: 'Cria links curtos com Bitly e slug custom opcional.',
    category: 'DevTools',
    keywords: ['shortener', 'url', 'bitly', 'slug'],
    path: '/tools/link-shortener',
    examples: ['https://example.com'],
  },
  {
    slug: 'json-formatter',
    name: 'Formatador de JSON',
    description: 'Valida, formata, minifica e ordena chaves.',
    category: 'DevTools',
    keywords: ['json', 'formatter', 'parse', 'minify'],
    path: '/tools/json-formatter',
    examples: ['{"a":1,"b":2}'],
  },
  {
    slug: 'sql-formatter',
    name: 'Formatador de SQL',
    description: 'Formata SQL com dialect e estilo configuravel.',
    category: 'DevTools',
    keywords: ['sql', 'formatter', 'postgres', 'mysql'],
    path: '/tools/sql-formatter',
    examples: ['select * from users'],
  },
  {
    slug: 'regex-tester',
    name: 'Testador de Regex',
    description: 'Executa regex com grupos e destaque de matches.',
    category: 'DevTools',
    keywords: ['regex', 'match', 'groups', 'flags'],
    path: '/tools/regex-tester',
    examples: ['/(foo|bar)/gi'],
  },
  {
    slug: 'text-diff',
    name: 'Comparacao de Texto',
    description: 'Diff inline e lado a lado com copia.',
    category: 'Texto',
    keywords: ['diff', 'compare', 'texto', 'patch'],
    path: '/tools/text-diff',
    examples: ['versao A vs B'],
  },
  {
    slug: 'markdown-viewer',
    name: 'Visualizador Markdown',
    description: 'Preview seguro com highlight de codigo.',
    category: 'Texto',
    keywords: ['markdown', 'preview', 'md', 'xss'],
    path: '/tools/markdown-viewer',
    examples: ['# Titulo'],
  },
  {
    slug: 'color-converter',
    name: 'Conversor de Cor',
    description: 'Converte HEX, RGB, HSL e HSV.',
    category: 'Cores',
    keywords: ['hex', 'rgb', 'hsl', 'hsv'],
    path: '/tools/color-converter',
    examples: ['#ff9900'],
  },
  {
    slug: 'image-compressor',
    name: 'Compressao de Imagens',
    description: 'Comprime e converte imagens via Sharp.',
    category: 'Arquivos',
    keywords: ['image', 'compress', 'sharp', 'webp'],
    path: '/tools/image-compressor',
    examples: ['PNG para WEBP'],
  },
  {
    slug: 'pdf-compressor',
    name: 'Compressao de PDFs',
    description: 'Comprime PDFs com fallback seguro.',
    category: 'Arquivos',
    keywords: ['pdf', 'compress', 'ghostscript'],
    path: '/tools/pdf-compressor',
    examples: ['Arquivo de 10MB'],
  },
];

export const categories = [
  'Identidade',
  'Texto',
  'Segurança',
  'Encoding',
  'DevTools',
  'Arquivos',
  'Cores',
] as const;

export function getToolBySlug(slug: string) {
  return toolDefinitions.find((tool) => tool.slug === slug);
}
